name: Test Stuff

on:
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: docker build and push
        uses: gat786/composite-actions/read-files@main
        