name: Test Stuff

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: docker build and push
        uses: gat786/composite-actions/read-files@main
        with:
          required_variable: "BARBIE"
          # optional_variable: "KEN"
        